# Generated by Django 5.0.4 on 2024-05-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='amount_of_money',
            field=models.FloatField(help_text='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.discount'),
        ),
    ]
