# Generated by Django 5.0.4 on 2024-05-12 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_orderinfo_amount_of_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Unique ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата добавления')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления')),
                ('text', models.TextField(help_text='О компании')),
            ],
            options={
                'db_table': 'about_company_table',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Unique ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата добавления')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления')),
                ('title', models.CharField(help_text='Заголовок', max_length=50)),
                ('text', models.TextField(help_text='Текст статьи')),
                ('img', models.ImageField(blank=True, help_text='Фотография', null=True, upload_to='app/static/main/img')),
            ],
            options={
                'db_table': 'news_table',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Unique ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата добавления')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления')),
                ('text', models.TextField(help_text='Политика конфиденфиальности')),
            ],
            options={
                'db_table': 'company_policy_table',
            },
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Unique ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата добавления')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления')),
                ('question', models.TextField(help_text='Question')),
                ('answer', models.TextField(help_text='Answer')),
            ],
            options={
                'db_table': 'qa_table',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Unique ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата добавления')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления')),
                ('name', models.CharField(help_text='Вакансия', max_length=50)),
                ('description', models.TextField(help_text='Описание вакансии')),
            ],
            options={
                'db_table': 'vacancies_table',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeesInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Unique ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата добавления')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления')),
                ('img', models.ImageField(blank=True, help_text='Фотография сотрудника', null=True, upload_to='app/static/main/img')),
                ('work', models.TextField(help_text='Его задачи')),
                ('other_inf', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.employee')),
            ],
            options={
                'db_table': 'employeesyInf_table',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, help_text='Unique ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата добавления')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата последнего обновления')),
                ('rate', models.PositiveSmallIntegerField(help_text='Оценка')),
                ('text', models.TextField(help_text='Текст отзыва')),
                ('user', models.ForeignKey(help_text='Отправитель', on_delete=django.db.models.deletion.CASCADE, to='main.customer')),
            ],
            options={
                'db_table': 'customer_reviews_table',
                'ordering': ['rate'],
            },
        ),
    ]
